#!/usr/bin/env python3
"""Gallery collision migration executor (P4B, write).

Executes the plan produced by ``scripts/plan_gallery_collision_migration.py``.

For each collision group this script:

* **Winners (11)**: copies the existing on-disk image, metadata, and
  two thumbnails (256, 512) from the old collision basename to the
  new ``<stable_id>`` filename. The source files are kept on disk so
  the executor can be re-run safely, but the index/web data layer
  is rewritten to point only at the new paths.

* **Losers (13)**: re-fetches the source_url via playwright, downloads
  the original image, writes a fresh metadata file, and regenerates
  the two thumbnails. A loser that fails to download (page 404,
  captcha, network timeout, etc.) is recorded in
  ``unresolved_losers.json`` and **does not** receive an entry in the
  rebuilt index/web data.

* **Index / web data**: rewrites ``index/artworks.csv`` so every
  collision record's ``local_image_path`` and ``metadata_path`` point
  at the new stable filename. Losers that fail are dropped from the
  index. ``web/data/artworks.json`` is then regenerated by running
  ``scripts/build_artvee_gallery.py --mode local``.

The script does **not** touch the public GitHub repo, the GitHub
Pages dist, the nightly manifest, or any file outside the local
project. It is intended to be run once and then committed alongside
the new code in ``scripts/artvee_identity.py`` and
``scripts/plan_gallery_collision_migration.py``.

Usage
-----

::

    python3 scripts/execute_gallery_collision_migration.py
    python3 scripts/execute_gallery_collision_migration.py --plan-json reports/runtime/p4b-collision-migration-plan.json
    python3 scripts/execute_gallery_collision_migration.py --dry-run
"""
from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
import traceback
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

# Stable id helpers are imported by the planner and build scripts
# (see scripts/plan_gallery_collision_migration.py and
# scripts/build_artvee_gallery.py). The executor itself reads the
# pre-computed ``new_image_path`` / ``new_metadata_path`` straight
# from the plan JSON, so it does not need to call them again.

# Reuse the existing browser-based downloader for losers.
import download_artvee_selected as dav  # noqa: E402
from build_artvee_gallery import (  # noqa: E402
    THUMBS_256_DIR,
    THUMBS_512_DIR,
    make_thumb,
)

INDEX_PATH = ROOT / "index" / "artworks.csv"
WEB_JSON_PATH = ROOT / "web" / "data" / "artworks.json"
IMAGES_DIR = ROOT / "images"
METADATA_DIR = ROOT / "metadata"
DEFAULT_PLAN = ROOT / "reports" / "runtime" / "p4b-collision-migration-plan.json"
UNRESOLVED_PATH = ROOT / "reports" / "runtime" / "p4b-unresolved-losers.json"
MIGRATION_LOG_PATH = ROOT / "reports" / "runtime" / "p4b-migration-log.json"


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _relpath_for_log(p: Path) -> str:
    """Return a path string safe to write to JSON log files."""
    try:
        return str(p.relative_to(ROOT))
    except ValueError:
        return str(p)


def _winner_rename(
    rec: dict[str, Any],
    log: dict[str, Any],
) -> tuple[Path, Path]:
    """Copy winner's image/metadata/thumbs to the new stable location.

    Returns ``(new_image_path, new_metadata_path)`` (relative to ROOT).
    The source files are kept on disk for safety (we may re-run).
    """
    old_img = ROOT / rec["old_image_path"]
    old_meta = ROOT / rec["old_metadata_path"]
    new_img_rel = rec["new_image_path"]
    new_meta_rel = rec["new_metadata_path"]
    new_img = ROOT / new_img_rel
    new_meta = ROOT / new_meta_rel
    new_img.parent.mkdir(parents=True, exist_ok=True)
    new_meta.parent.mkdir(parents=True, exist_ok=True)

    # Copy image (read+write — never move, to keep recovery possible)
    if old_img.exists():
        shutil.copy2(old_img, new_img)
    else:
        raise FileNotFoundError(f"winner image missing: {old_img}")

    # Update metadata copy with the new local_image_path field
    if old_meta.exists():
        with old_meta.open("r", encoding="utf-8") as f:
            meta_obj = json.load(f)
        meta_obj["local_image_path"] = new_img_rel
        with new_meta.open("w", encoding="utf-8") as f:
            json.dump(meta_obj, f, ensure_ascii=False, indent=2)
    else:
        raise FileNotFoundError(f"winner metadata missing: {old_meta}")

    # Copy thumbs (regenerate from the new image to be safe)
    for size, thumbs_dir in [(256, THUMBS_256_DIR), (512, THUMBS_512_DIR)]:
        dst = thumbs_dir / Path(new_img_rel).name
        if new_img.exists():
            try:
                make_thumb(new_img, dst, size)
            except Exception as e:
                # Fall back to copying the old thumb if regen fails
                old_thumb = thumbs_dir / Path(rec["old_image_path"]).name
                if old_thumb.exists():
                    shutil.copy2(old_thumb, dst)
                else:
                    log.setdefault("thumb_errors", []).append(
                        {"size": size, "error": str(e), "file": _relpath_for_log(dst)}
                    )

    log["winners_renamed"] = log.get("winners_renamed", 0) + 1
    return new_img, new_meta


def _loser_redownload(
    rec: dict[str, Any],
    row_idx: int,
    log: dict[str, Any],
) -> tuple[Path, Path] | None:
    """Re-fetch a single loser artwork via playwright + urllib.

    Returns ``(new_image_path, new_metadata_path)`` on success, or
    ``None`` on failure (in which case an entry is appended to
    ``log['unresolved_losers']``).
    """
    src = rec["source_url"]
    category = rec["category"]
    variant = rec["variant"] or "standard"
    tags = ""
    usage_note = ""

    new_img_rel = rec["new_image_path"]
    new_meta_rel = rec["new_metadata_path"]
    new_img = ROOT / new_img_rel
    new_meta = ROOT / new_meta_rel
    new_img.parent.mkdir(parents=True, exist_ok=True)
    new_meta.parent.mkdir(parents=True, exist_ok=True)

    try:
        artist, title, dl_url = dav.fetch_page_with_browser(src, row_idx)
    except Exception as e:
        log.setdefault("unresolved_losers", []).append(
            {
                "source_url": src,
                "new_stable_id": rec["new_stable_id"],
                "phase": "fetch",
                "error": str(e),
            }
        )
        return None

    # Determine extension from the actual download URL
    ext = ".jpg"
    dl_l = dl_url.lower()
    if ".png" in dl_l:
        ext = ".png"
    elif ".jpeg" in dl_l:
        ext = ".jpeg"
    new_img_rel = rec["new_image_path"]
    # If ext differs, write with the actual ext
    if not new_img_rel.endswith(ext):
        new_img_rel = new_img_rel[: -len(".jpg")] + ext
        new_img = ROOT / new_img_rel
    try:
        dav.download_image(dl_url, new_img)
    except Exception as e:
        log.setdefault("unresolved_losers", []).append(
            {
                "source_url": src,
                "new_stable_id": rec["new_stable_id"],
                "phase": "download",
                "error": str(e),
            }
        )
        return None

    # Try to read category/tags/usage_note from the old index row
    # (these don't change between old and new layout)
    try:
        irows = _read_index()
        for r in irows:
            if r.get("source_url", "").strip() == src:
                tags = r.get("tags", "")
                usage_note = r.get("usage_note", "")
                break
    except Exception:
        pass

    # Write metadata in the same shape as run_artvee_nightly_batch.py
    norm_artist = artist.replace(" ", "_") if artist else ""
    norm_title = title.replace(" ", "_") if title else ""
    metadata = {
        "source": "artvee.com",
        "url": src,
        "artist": norm_artist,
        "title": norm_title,
        "category": category,
        "download_variant": variant,
        "tags": tags,
        "usage_note": usage_note,
        "local_image_path": new_img_rel,
        "raw_artist": artist,
        "raw_title": title,
        "normalized_artist": norm_artist,
        "normalized_title": norm_title,
        "downloaded_at": datetime.now().isoformat(timespec="seconds"),
        "file_exists": True,
    }
    new_meta.write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")

    # Generate thumbs
    for size, thumbs_dir in [(256, THUMBS_256_DIR), (512, THUMBS_512_DIR)]:
        dst = thumbs_dir / Path(new_img_rel).name
        try:
            make_thumb(new_img, dst, size)
        except Exception as e:
            log.setdefault("thumb_errors", []).append(
                {"size": size, "error": str(e), "file": _relpath_for_log(dst)}
            )

    log["losers_redownloaded"] = log.get("losers_redownloaded", 0) + 1
    return new_img, new_meta


def _read_index() -> list[dict[str, str]]:
    if not INDEX_PATH.exists():
        return []
    with INDEX_PATH.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _rewrite_index(plan: dict[str, Any], log: dict[str, Any]) -> int:
    """Rewrite index/artworks.csv with the new stable_id paths.

    Returns the number of rewritten collision rows. Rows in
    collision groups that the plan could not produce a successful
    file for (unresolved losers) are **dropped**: their old
    local_image_path now points at the renamed winner's file, so
    keeping them would create the exact same collision P4B is
    trying to fix.

    The 4-row drop is graceful: the unresolved list is recorded
    in ``reports/runtime/p4b-unresolved-losers.json`` and the
    executor does not touch any other index row.
    """
    irows = _read_index()

    # Set of every source_url that appears in any collision group.
    collision_urls: set[str] = set()
    # Map source_url -> new paths (only for winners + successful losers)
    url_to_new: dict[str, dict[str, str]] = {}
    for g in plan["groups"]:
        for r in g["records"]:
            collision_urls.add(r["source_url"])
            new_img_rel = r["new_image_path"]
            new_meta_rel = r["new_metadata_path"]
            new_img_path = ROOT / new_img_rel
            new_meta_path = ROOT / new_meta_rel
            if new_img_path.exists() and new_meta_path.exists():
                url_to_new[r["source_url"]] = {
                    "new_image_path": new_img_rel,
                    "new_metadata_path": new_meta_rel,
                }

    new_rows: list[dict[str, str]] = []
    rewritten = 0
    dropped = 0
    for r in irows:
        src = r.get("source_url", "").strip()
        if src in collision_urls:
            if src in url_to_new:
                upd = dict(r)
                upd["local_image_path"] = url_to_new[src]["new_image_path"]
                upd["metadata_path"] = url_to_new[src]["new_metadata_path"]
                new_rows.append(upd)
                rewritten += 1
            else:
                # Failed loser: drop, because its old path is the
                # renamed winner's file (different artwork content).
                dropped += 1
        else:
            new_rows.append(r)

    # Write back
    fieldnames = list(new_rows[0].keys()) if new_rows else [
        "artist", "title", "category", "download_variant", "tags",
        "usage_note", "source_url", "local_image_path", "metadata_path",
    ]
    with INDEX_PATH.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(new_rows)

    log["index_rewritten_rows"] = rewritten
    log["index_dropped_unresolved"] = dropped
    log["index_total_rows_after"] = len(new_rows)
    return rewritten


def _regenerate_web(log: dict[str, Any]) -> None:
    """Re-run build_artvee_gallery.py to regenerate web/data/artworks.json.

    Imports the module's ``main`` and re-runs it. (avoids subprocess.)
    """
    import build_artvee_gallery as bg  # noqa: E402

    rc = bg.main(["--mode", "local"])  # type: ignore[arg-type]
    log["build_artvee_gallery_exit"] = rc


def run(plan_path: Path, dry_run: bool) -> dict[str, Any]:
    plan = _read_json(plan_path)
    log: dict[str, Any] = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "plan_path": _relpath_for_log(plan_path),
        "dry_run": dry_run,
        "winners_renamed": 0,
        "losers_redownloaded": 0,
        "unresolved_losers": [],
        "thumb_errors": [],
    }

    if dry_run:
        log["dry_run_would"] = "skip all file operations; print plan summary only"
        return log

    # 1) winners — rename
    print("== Step 1/4: rename 11 winners ==")
    for g in plan["groups"]:
        for r in g["records"]:
            if r["role"] == "winner":
                _winner_rename(r, log)
                print(f"  ✅ winner renamed: {r['new_image_path']}")

    # 2) losers — re-download (≤ 13)
    print("\n== Step 2/4: re-download 13 losers ==")
    row_idx = 0
    for g in plan["groups"]:
        for r in g["records"]:
            if r["role"] == "loser":
                row_idx += 1
                print(f"  [{row_idx}/13] fetching: {r['source_url']}")
                result = _loser_redownload(r, row_idx, log)
                if result is None:
                    print(f"    ❌ UNRESOLVED (see unresolved_losers)")
                else:
                    print(f"    ✅ downloaded: {_relpath_for_log(result[0])}")

    # 3) rewrite index
    print("\n== Step 3/4: rewrite index/artworks.csv ==")
    n = _rewrite_index(plan, log)
    print(f"  ✅ index rewritten: {n} collision rows updated, total {log['index_total_rows_after']} rows")

    # 4) regenerate web
    print("\n== Step 4/4: regenerate web/data/artworks.json ==")
    try:
        _regenerate_web(log)
        print(f"  ✅ build_artvee_gallery exit={log.get('build_artvee_gallery_exit')}")
    except Exception as e:
        log["build_artvee_gallery_error"] = str(e)
        log["build_artvee_gallery_traceback"] = traceback.format_exc()
        print(f"  ❌ build_artvee_gallery failed: {e}")

    log["finished_at"] = datetime.now().isoformat(timespec="seconds")
    return log


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="P4B gallery collision migration executor"
    )
    p.add_argument(
        "--plan-json",
        type=Path,
        default=DEFAULT_PLAN,
        help=f"Path to plan JSON (default: {DEFAULT_PLAN.relative_to(ROOT)}).",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen; do not modify any file.",
    )
    args = p.parse_args(argv)

    if not args.plan_json.exists():
        print(f"ERROR: plan JSON not found: {args.plan_json}", file=sys.stderr)
        return 2

    log = run(args.plan_json, dry_run=args.dry_run)

    # Always write the log + unresolved-losers file
    _write_json(MIGRATION_LOG_PATH, log)
    unresolved = log.get("unresolved_losers", [])
    if unresolved:
        _write_json(UNRESOLVED_PATH, unresolved)
    else:
        # Remove stale unresolved file if any
        if UNRESOLVED_PATH.exists():
            UNRESOLVED_PATH.unlink()

    print()
    print("== Summary ==")
    print(f"  winners renamed:       {log.get('winners_renamed', 0)}")
    print(f"  losers re-downloaded:  {log.get('losers_redownloaded', 0)}")
    print(f"  unresolved losers:     {len(unresolved)}")
    print(f"  index rows rewritten:  {log.get('index_rewritten_rows', 0)}")
    print(f"  index total rows:      {log.get('index_total_rows_after', '?')}")
    print(f"  build_artvee_gallery:  exit={log.get('build_artvee_gallery_exit', 'n/a')}")
    print()
    print(f"Migration log: {_relpath_for_log(MIGRATION_LOG_PATH)}")
    if unresolved:
        print(f"Unresolved losers: {_relpath_for_log(UNRESOLVED_PATH)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
